/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.18).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.csme.csmeapi.api;

import java.util.Optional;
import java.util.UUID;

import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.csme.csmeapi.fin.models.IntroResponse;
import com.fasterxml.jackson.databind.ObjectMapper;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2024-09-23T22:57:54.741+04:00[Asia/Muscat]")
@Api(value = "Intro", description = "the Intro API")
public interface IntroApi {

    Logger log = LoggerFactory.getLogger(IntroApi.class);

    Optional<ObjectMapper> getObjectMapper();

    Optional<HttpServletRequest> getRequest();

    

    @ApiOperation(value = "Introduction", nickname = "introduction", notes = "", response = IntroResponse.class, authorizations = {
        @Authorization(value = "jwt")    }, tags={ "Introduction", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = IntroResponse.class),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/Intro",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<IntroResponse> introduction(@ApiParam(value = "Request Id" ,required=true) @RequestHeader(value="requestId", required=true) UUID requestId
,@ApiParam(value = "Channel Name" ,required=true, defaultValue="FinMobileBankingApp") @RequestHeader(value="channel", required=true) String channel
,@ApiParam(value = "Time date Unix Format" ,required=true) @RequestHeader(value="timeStamp", required=true) Integer timeStamp
,@ApiParam(value = "Secert Key" ) @RequestHeader(value="SecertKey", required=false) String secertKey
,@ApiParam(value = "Version of API" , defaultValue="1.0.0") @RequestHeader(value="version", required=false) String version
);

}
